// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1649619884);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1649619284);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1649620562);
user_pref("app.update.lastUpdateTime.region-update-timer", 1649620124);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1649619524);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1649619404);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1649619764);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1649619314);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1649620004);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{2d2f6439-b863-485c-afcc-89731c293e1f}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1649619254);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 125);
user_pref("browser.newtabpage.activity-stream.discoverystream.rec.impressions", "{\"125136\":1649620604395,\"125172\":1649620604393,\"125176\":1649620604396}");
user_pref("browser.newtabpage.activity-stream.impressionId", "{bc4496ee-f271-4c70-9a90-82470415f460}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1649620125);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1649621093457");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1649622873457");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1649619268548");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1649640868548");
user_pref("browser.search.region", "IN");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1649619254");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20220404170724");
user_pref("browser.startup.homepage_override.mstone", "99.0");
user_pref("browser.startup.lastColdStartupCheck", 1649619255);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1649619260411");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "99.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "IN");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "7a01c3db50b54648bac6a1e7f438c509");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1649619886);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20220404170724");
user_pref("extensions.lastAppVersion", "99.0");
user_pref("extensions.lastPlatformVersion", "99.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"b4ad7c1b-c093-4c93-b87a-c2c2b702dfec\",\"formautofill@mozilla.org\":\"9058466e-cc17-4a5f-b33c-2eca0ab358bf\",\"pictureinpicture@mozilla.org\":\"8cbbf1d1-20bc-4f0e-b341-063149fd48c6\",\"screenshots@mozilla.org\":\"d2314655-fa8d-47c9-89ad-51c0c244433f\",\"webcompat-reporter@mozilla.org\":\"0979a13e-b791-4bb0-a955-b40ca97ecfd5\",\"webcompat@mozilla.org\":\"34bf4852-8c3d-425a-abe4-ff5c3449cbcf\",\"default-theme@mozilla.org\":\"67882bb4-7fb3-4748-9cdd-81effd0f0627\",\"addons-search-detection@mozilla.com\":\"14db2823-7c81-428b-9d23-7494afeb8ec3\",\"google@search.mozilla.org\":\"c0c515da-84e0-40c1-b8c5-4d05aac4cc7d\",\"wikipedia@search.mozilla.org\":\"f4cc5c53-556f-4ea6-b166-7634eaa5a003\",\"bing@search.mozilla.org\":\"53cd527b-520d-42aa-adad-287defe398e4\",\"ddg@search.mozilla.org\":\"ba352700-3928-4535-97f5-56a567f343ac\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1649619260);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("gfx.blacklist.webrender", 4);
user_pref("gfx.blacklist.webrender.failureid", "FEATURE_FAILURE_DDX_INTEL");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1649619887);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20220404170724");
user_pref("media.gmp-manager.lastCheck", 1649620525);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "62cf7d5b-6ef4-4bca-b118-236cd09d7991");
user_pref("services.blocklist.addons-mlbf.checked", 1649620527);
user_pref("services.blocklist.gfx.checked", 1649620527);
user_pref("services.settings.clock_skew_seconds", 47);
user_pref("services.settings.last_update_seconds", 1649620527);
user_pref("services.settings.main.message-groups.last_check", 1649620527);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1649620527);
user_pref("services.settings.main.top-sites.last_check", 1649620527);
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1649619253);
user_pref("toolkit.telemetry.cachedClientID", "626177b7-6b8e-4db3-9403-2a16ab477a30");
user_pref("toolkit.telemetry.previousBuildID", "20220404170724");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
